apiVersion: apps/v1
kind: Statefulset
metadata: 
  name: postgres-db
spec: 
  serviceName: "postgres"
  replicas: 1
  selector: 
    matchLables:
      app: postgres
  template: 
    metadata:
    labels: 
      app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPost: 5432


---

apiVersion: v1
kind: Service
metadata: 
  name; db-service
spec: 
  selector: 
    app: postgres
  ports: 
    - protocol: TCP
      port: 5432
