apiVersion: v1
data:
  nginx.conf: "events { worker_connections 1024; }\nhttp {\n    include       /etc/nginx/mime.types;\n
    \   default_type  application/octet-stream;\n    \n    server {\n        listen
    80;\n        \n        location / {\n            root /usr/share/nginx/html;\n
    \           index index.html index.htm;\n            try_files $uri $uri/ /index.html;\n
    \       }\n\n        location /api/ {\n            proxy_pass http://backend-service:80/;\n
    \           proxy_set_header Host $host;\n            proxy_set_header X-Real-IP
    $remote_addr;\n            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n
    \       }\n    }\n}\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"nginx.conf":"events { worker_connections 1024; }\nhttp {\n    include       /etc/nginx/mime.types;\n    default_type  application/octet-stream;\n    \n    server {\n        listen 80;\n        \n        location / {\n            root /usr/share/nginx/html;\n            index index.html index.htm;\n            try_files $uri $uri/ /index.html;\n        }\n\n        location /api/ {\n            proxy_pass http://backend-service:80/;\n            proxy_set_header Host $host;\n            proxy_set_header X-Real-IP $remote_addr;\n            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        }\n    }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"frontend-config","namespace":"default"}}
  name: frontend-config
  namespace: default
